name: Upload Hello.go to S3
on:
  push:
    branches:
      - master

jobs:
  publish_message:
    name: Upload Hello.go File to S3
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: publish file to s3
        uses: mrkresnofatih/gha-upload-file-to-s3@master
        with:
          FILE_PATH: ./Hello.go
          AWS_KEY: ${{secrets.AWS_KEY}}
          AWS_SECRET: ${{secrets.AWS_SECRET}}
          AWS_REGION: ap-southeast-1
          BUCKET_URL: sg-lambda-store/rml
          FILE_NAME: Hello.go
